name: Build and deploy .NET Core application to Function App ngt2024
on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
 id-token: write
 contents: read

env:
  AZURE_FUNCTIONAPP_NAME: ngt2024
  # AZURE_FUNCTIONAPP_PACKAGE_PATH: src\DurableFunctionOrchestration\published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src\DurableFunctionOrchestration
  DOTNET_CORE_VERSION_INPROC: 6.0.x
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
  
    - name: Setup .NET ${{ env.DOTNET_VERSION }} SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --output ./output
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: 'Publish Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

        
