name: Build and deploy .NET application to Function App
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src\DurableFunctionOrchestration

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }} SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --output ./output
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: "Publish Azure Function"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}/output
